services:
  - type: web
    name: nexus-ems-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build -w apps/backend
    startCommand: npm run start -w apps/backend
    envVars:
      - key: NODE_ENV
        value: production
    rootDirectory: .
